[tools]
rotrieve = { source = "roblox/rotriever", version = "0.5.8" }
rojo = { source = "rojo-rbx/rojo", version = "7.2.1" }
selene = { source = "Kampfkarren/selene", version = "0.22.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.15.1" }
