[tools]
rotrieve = { source = "roblox/rotriever", version = "=0.5.6" }
rojo = { source = "rojo-rbx/rojo", version = "6.2.0" }
selene = { source = "Kampfkarren/selene", version = "0.21.1" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.15.1" }
