[package]
name = "PerformanceBenchmarks"
version = "0.1.0"
authors = ["Roblox"]
content_root = "src"

[dependencies]
LuauPolyfill = "github.com/roblox/luau-polyfill@1"
Promise = "github.com/roblox/roblox-lua-promise@3.3.0"
Cryo = "github.com/Roblox/cryo@1.0.0"

[dev_dependencies]
Roact = { target = "github.com/roblox/roact-alignment", package = "React", version = "17.0.1-rc.16" }
ReactRoblox = "github.com/roblox/roact-alignment@17.0.1-rc.16"
Scheduler = "github.com/roblox/roact-alignment@17.0.1-rc.16"
Jest = "github.com/roblox/jest-roblox@3"
JestGlobals = "github.com/roblox/jest-roblox@3"
