[package]
name = "concurrent-lua"
version = "0.1.0"
author = "Roblox"
content_root = "src"

# Optional fields and their definitions can be found at:
# https://pages.github.rbx.com/pdoyle/rotriever-docs/reference/manifest-format/#manifest-fields

[dependencies]
LuauPolyfill = "github.com/Roblox/luau-polyfill@0.2.0"
Promise = "github.com/evaera/roblox-lua-promise@3.0.1"
Roact = { git = "https://github.com/roblox/roact-alignment.git", rev = "master", package = "React" }
ReactRoblox = { git = "https://github.com/roblox/roact-alignment.git", rev = "master" }
Scheduler = { git = "https://github.com/roblox/roact-alignment.git", rev = "master" }
Cryo = "github.com/Roblox/cryo@1.0.0"

[dev_dependencies]
JestRoblox = "github.com/roblox/jest-roblox@1.0.0"
