[package]
name = "PerformanceBenchmarks"
version = "0.1.0"
author = "Roblox"
content_root = "src"

[dependencies]
LuauPolyfill = "github.com/roblox/luau-polyfill@roblox/roblox-luau-polyfill@0.2.0"
Promise = "github.com/evaera/roblox-lua-promise@3.1.0"
Cryo = "github.com/Roblox/cryo@1.0.0"

[dev_dependencies]
Roact = { git = "https://github.com/roblox/roact-alignment.git", package = "React" }
ReactRoblox = { git = "https://github.com/roblox/roact-alignment.git" }
Scheduler = { git = "https://github.com/roblox/roact-alignment.git" }
JestRoblox = "github.com/roblox/jest-roblox@=1.1.2"
# FIXME: This project is not intended for use outside of roact-alignment
RobloxJest = { git = "https://github.com/roblox/roact-alignment.git" }
